steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_REPO_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_REPO_NAME}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', '${_SERVICE_NAME}',
    '--image', 'gcr.io/$PROJECT_ID/${_REPO_NAME}',
    '--region', '${_DEPLOY_REGION}',
    '--platform', '${_PLATFORM}',
    '--set-env-vars', 'OPENAI_API_KEY=${_OPENAI_API_KEY},FIREBASE_CREDENTIALS_PATH=${_FIREBASE_CREDENTIALS_PATH},FIRESTORE_PROJECT_ID=${_FIRESTORE_PROJECT_ID},FIRESTORE_EMULATOR_HOST=${_FIRESTORE_EMULATOR_HOST}'
  ]
images:
  - 'gcr.io/$PROJECT_ID/learnifycode-backend:latest'
options:
  logging: CLOUD_LOGGING_ONLY
